
package org.mpilone.vaadin.timeline;

import java.util.UUID;

/**
 * An implementation of a timeline group.
 *
 * @author mpilone
 */
public class BasicTimelineGroup implements TimelineGroup {

  private String styleName;
  private String content;
  private String id;
  private String style;
  private String subgroupOrder;
  private String title;
  private String order;

  /**
   * Constructs the group which will have an ID generated by {@link UUID}, an
   * empty string caption, and no style name.
   */
  public BasicTimelineGroup() {
    this(UUID.randomUUID().toString(), "", null);
  }

  /**
   * Constructs the group.
   *
   * @param id the unique ID of the group that will be referenced by items
   * @param content the content to display as the group label
   * @param styleName the CSS style name(s) or null
   */
  public BasicTimelineGroup(String id, String content, String styleName) {
    this.id = id;
    this.content = content;
    this.styleName = styleName;
  }

  @Override
  public String getId() {
    return id;
  }

  @Override
  public String getContent() {
    return content;
  }

  @Override
  public String getStyleName() {
    return styleName;
  }

  @Override
  public String getStyle() {
    return style;
  }

  public void setStyle(String style) {
    this.style = style;
  }

  @Override
  public String getSubgroupOrder() {
    return subgroupOrder;
  }

  public void setSubgroupOrder(String subgroupOrder) {
    this.subgroupOrder = subgroupOrder;
  }

  @Override
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  @Override
  public String getOrder() {
    return order;
  }

  public void setOrder(String order) {
    this.order = order;
  }

  public void setStyleName(String styleName) {
    this.styleName = styleName;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public void setId(String id) {
    this.id = id;
  }

}
